spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 142212
    username: root
    url: jdbc:mysql://localhost:3307/springboot_myblog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  mvc:
    static-path-pattern: /**
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081